force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <label>Bus Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Buses</relationshipLabel>
    <relationshipName>Buses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Available&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>In Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bus_Line__c/Bus_Line__c.object-meta.xml
<CustomObject>
    <label>Bus_Line</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Bus Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bus Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus_Line__c/fields/Bus__c.field-meta.xml
<CustomField>
    <fullName>Bus__c</fullName>
    <label>Bus</label>
    <referenceTo>Bus__c</referenceTo>
    <relationshipLabel>Bus Lines</relationshipLabel>
    <relationshipName>Bus_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bus_Line__c/fields/Line__c.field-meta.xml
<CustomField>
    <fullName>Line__c</fullName>
    <label>Line</label>
    <referenceTo>Line__c</referenceTo>
    <relationshipLabel>Bus Lines</relationshipLabel>
    <relationshipName>Bus_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Line__c/Line__c.object-meta.xml
<CustomObject>
    <label>Line</label>
    <nameField>
        <label>Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BusListService.cls
public class BusListService {
    
    public static List<Bus__c> getAllBuses(String accountId) {
        List<Bus__c> buses;
        try {
            buses = [SELECT Id, Name, Status__c, Account__c, (SELECT Id, Bus__r.Id, Line__r.Name, Line__r.Id FROM Bus_Lines__r)
                     FROM Bus__c WHERE Account__c =: accountId WITH SECURITY_ENFORCED];
        } catch (QueryException e) {
            throw new NoAccessException('No access to object');
        }
        return buses;
    }
    
     public static void deleteCurrentBus(String busId) {
        Bus__c bus;
        try {
            bus = [SELECT Id, Name FROM Bus__c WHERE id =: busId WITH SECURITY_ENFORCED];
        } catch (QueryException e) {
            throw new NoAccessException('No access to object');
        }
        if (Schema.sObjectType.Bus__c.isDeletable()) {
            delete bus;
        }
    }
    
    public static void deleteCurrentLine(String lineId, String busId) {
        Bus_Line__c busLine;
        System.debug(lineId);
        try {
            busLine = [SELECT Id, Bus__c, Line__c FROM Bus_Line__c WHERE 
                       Bus__c =: busId AND Line__c =: lineId WITH SECURITY_ENFORCED];
            System.debug(busLine);
        } catch (QueryException e) {
            throw new NoAccessException('No access to object');
        }
        if (Schema.sObjectType.Bus__c.isDeletable()) {
            delete busLine;
        }
    }
}