force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <label>Bus Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Buses</relationshipLabel>
    <relationshipName>Buses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Available&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>In Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bus_Line__c/Bus_Line__c.object-meta.xml
<CustomObject>
    <label>Bus_Line</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Bus Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bus Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus_Line__c/fields/Bus__c.field-meta.xml
<CustomField>
    <fullName>Bus__c</fullName>
    <label>Bus</label>
    <referenceTo>Bus__c</referenceTo>
    <relationshipLabel>Bus Lines</relationshipLabel>
    <relationshipName>Bus_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bus_Line__c/fields/Line__c.field-meta.xml
<CustomField>
    <fullName>Line__c</fullName>
    <label>Line</label>
    <referenceTo>Line__c</referenceTo>
    <relationshipLabel>Bus Lines</relationshipLabel>
    <relationshipName>Bus_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Line__c/Line__c.object-meta.xml
<CustomObject>
    <label>Line</label>
    <nameField>
        <label>Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BusLineServiceTest.cls
@isTest
public class BusLineServiceTest {
      
    @testSetup static void setup() {
         Account account = new Account(Name='Test account');
         insert account;
         
         Bus__c bus = new Bus__c(Name='Test Bus', Account__c=Account.Id, Status__c='Available');
		 insert bus;	         
       
         Line__c line = new Line__c(Name='Test Line');
         insert line;
     }
    
   @isTest static void testChangeStatusBeforeInsert() {     
		Bus__c bus = [SELECT Id, Status__c FROM Bus__c WHERE Name='Test Bus' LIMIT 1]; 
     	Line__c line = [SELECT Id FROM Line__c WHERE Name='Test Line' LIMIT 1];
     
        Bus_Line__c busLine = new Bus_Line__c(Bus__c = bus.Id, Line__c = line.Id);
        insert busLine;
     
        System.assertEquals('In Use', [SELECT Id, Status__c FROM Bus__c 
                                       WHERE Name='Test Bus' LIMIT 1].Status__c);
     
    }
    
   @isTest static void testChangeStatusAfterDelete() {
       Bus__c bus = [SELECT Id, Status__c FROM Bus__c WHERE Name='Test Bus' LIMIT 1]; 
       Line__c line = [SELECT Id FROM Line__c WHERE Name='Test Line' LIMIT 1];
     
       Bus_Line__c busLine = new Bus_Line__c(Bus__c = bus.Id, Line__c = line.Id);
       insert busLine;
       delete busLine;
    
       System.assertEquals('Available', [SELECT Id, Status__c FROM Bus__c 
                                         WHERE Name = 'Test Bus' LIMIT 1].Status__c);
  }
}