force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <label>Bus Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus_Line__c/Bus_Line__c.object-meta.xml
<CustomObject>
    <label>Bus_Line</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Bus Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bus Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus_Line__c/fields/Bus__c.field-meta.xml
<CustomField>
    <fullName>Bus__c</fullName>
    <label>Bus</label>
    <referenceTo>Bus__c</referenceTo>
    <relationshipLabel>Bus Lines</relationshipLabel>
    <relationshipName>Bus_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bus_Line__c/fields/Line__c.field-meta.xml
<CustomField>
    <fullName>Line__c</fullName>
    <label>Line</label>
    <referenceTo>Line__c</referenceTo>
    <relationshipLabel>Bus Lines</relationshipLabel>
    <relationshipName>Bus_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Line__c/Line__c.object-meta.xml
<CustomObject>
    <label>Line</label>
    <nameField>
        <label>Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LineService.cls
public class LineService {
    
	 public static List<Line__c> getAllLines() {
        List<Line__c> lines;
        try {
            lines = [SELECT Id, Name FROM Line__c WITH SECURITY_ENFORCED];
        } catch (QueryException e) {
            throw new NoAccessException('No access to object');
        }
        return lines;
    }
    
     public static void addNewLine(String busId, String lineId) {
        System.debug(busId);
        System.debug(lineId);
        List<Bus_Line__c> busLines;
        try {
            busLines = [SELECT Id, Bus__c, Line__c FROM Bus_Line__c WHERE Bus__c =: busId AND Line__c =: lineId WITH SECURITY_ENFORCED];
        }
        catch (QueryException e) {
            throw new NoAccessException('No access to object');
        }
         if (busLines.size() >= 1) {
            throw new NoAccessException('No access to object');
         } else {
             Bus_Line__c newBusLine = new Bus_Line__c(Bus__c = busId, Line__c = lineId);
             insert newBusLine;
         }
    }
}