force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <label>Bus Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Available&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>In Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bus_Line__c/Bus_Line__c.object-meta.xml
<CustomObject>
    <label>Bus_Line</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Bus Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bus Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus_Line__c/fields/Bus__c.field-meta.xml
<CustomField>
    <fullName>Bus__c</fullName>
    <label>Bus</label>
    <referenceTo>Bus__c</referenceTo>
    <relationshipLabel>Bus Lines</relationshipLabel>
    <relationshipName>Bus_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BusLineService.cls
public class BusLineService {
    
    private static final String IN_USE = 'In Use';
    private static final String AVAILABLE = 'Available';
    
    public void changeStatusBeforeInsert(List<Bus_Line__c> busLines) {
        List<Bus__c> buses = getRelatedBuses(busLines);
        for (Bus__c bus : buses) {
            bus.Status__c = IN_USE;
        }
        if (Schema.sObjectType.Bus__c.isUpdateable()) {
            update buses;
        }
    }
    
    public void changeStatusAfterDelete(List<Bus_Line__c> busLines) {
        List<Bus__c> buses = getRelatedBuses(busLines);
        for (Bus__c bus : buses) {
            if (bus.Bus_Lines__r.isEmpty()) {
                bus.Status__c = AVAILABLE;
            }
        }
        if (Schema.sObjectType.Bus__c.isUpdateable()) {
            update buses;
        }
    }
    
    public List<Bus__c> getRelatedBuses(List<Bus_Line__c> busLines) {
        List<Id> busIds = new List<Id>();
        for (Bus_Line__c busLine : busLines) {
            busIds.add(busLine.Bus__c);
        }
        List<Bus__c> buses = new List<Bus__c>();
        try {
            buses = [SELECT Id, Status__c, (SELECT Id FROM Bus_Lines__r) 
                     FROM Bus__c WHERE Id IN :busIds WITH SECURITY_ENFORCED];
        } catch (QueryException e) {
            throw new NoAccessException('No Access To Object');
        } 
        return buses; 
    }
}